# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f51d3cbd2aea551b655b9436d93ec886257f5287380c222a3679a6b2f58e52685cd6e71efc434099694e275d770c4ccfbae4a49012b81af851292c402cc3f26

test:
  secret_key_base: d9c142e6167a898248fe01494ffcc2f03eaef3a3ccd0a4aa721ec932fec6b214c61fdaa3bd7b63295427ab3790e8acf4571d8f6c7ea9e7d48e8bf07919850e01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
